### ISSUE TITLE
Touchscreen won't work on iPhone 7 Plus

### ISSUE THREAD

**Issue by randomusernamehi** [corellium/projectsandcastle#16] opened 2020-03-05 20:26 UTC
I did replace my screen with something else, but the screen itself does work, just not the touch screen, the touchscreen works in iOS so it can't be that different from the factory default, but it won't work in Android, I'm assuming that's the reason why but it might be something else possibly.

**Comment by rootedetc** [comment] 2020-03-06 07:07
The issue is already open, no need to open a second one.
https://github.com/corellium/projectsandcastle/issues/10#issue-576094984

**Comment by Stan-Corellium** [comment] 2020-03-09 00:07
Closing as duplicate of #10 . If you can program a bit and can help debug this, please head over there.

**Closed by Stan-Corellium** 2020-03-09 00:07 UTC
